# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(969, 699)
        font = QtGui.QFont()
        font.setPointSize(15)
        Dialog.setFont(font)
        self.widget = QtWidgets.QWidget(parent=Dialog)
        self.widget.setGeometry(QtCore.QRect(30, 20, 652, 451))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.listofuser = QtWidgets.QListWidget(parent=self.widget)
        self.listofuser.setObjectName("listofuser")
        self.gridLayout.addWidget(self.listofuser, 11, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 6, 0, 2, 1)
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 2, 3)
        self.pushButton_savetofile = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_savetofile.setObjectName("pushButton_savetofile")
        self.gridLayout.addWidget(self.pushButton_savetofile, 11, 1, 1, 1)
        self.umowaoprace = QtWidgets.QCheckBox(parent=self.widget)
        self.umowaoprace.setObjectName("umowaoprace")
        self.gridLayout.addWidget(self.umowaoprace, 9, 0, 1, 5)
        self.save = QtWidgets.QPushButton(parent=self.widget)
        self.save.setObjectName("save")
        self.gridLayout.addWidget(self.save, 11, 0, 1, 1)
        self.secondname = QtWidgets.QLineEdit(parent=self.widget)
        self.secondname.setObjectName("secondname")
        self.gridLayout.addWidget(self.secondname, 3, 4, 1, 1)
        self.name = QtWidgets.QLineEdit(parent=self.widget)
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 1, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 2, 4)
        self.numberofphone = QtWidgets.QLineEdit(parent=self.widget)
        self.numberofphone.setObjectName("numberofphone")
        self.gridLayout.addWidget(self.numberofphone, 4, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout.addLayout(self.verticalLayout, 9, 7, 3, 1)
        self.label_5 = QtWidgets.QLabel(parent=self.widget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 10, 4, 1, 1)
        self.pesel = QtWidgets.QLineEdit(parent=self.widget)
        self.pesel.setMaxLength(11)
        self.pesel.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.pesel.setObjectName("pesel")
        self.gridLayout.addWidget(self.pesel, 7, 4, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_4.setText(_translate("Dialog", "Pesel"))
        self.label.setText(_translate("Dialog", "Imie"))
        self.pushButton_savetofile.setText(_translate("Dialog", "Zapisz do pliku"))
        self.umowaoprace.setText(_translate("Dialog", "Umowa o pracę"))
        self.save.setText(_translate("Dialog", "zapisz"))
        self.label_2.setText(_translate("Dialog", "Nazwisko"))
        self.label_3.setText(_translate("Dialog", "Numer telefonu"))
        self.label_5.setText(_translate("Dialog", "Użytkownicy z peselem"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
